version: '3.8'
services:
  scoreService:
    container_name: ScoreApplication
    image: score-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: "java -jar app.jar"
